receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317

exporters:
  prometheus:
    endpoint: otel-collector:8889
  otlp:
    endpoint: i3lab-dashboard:18889
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:
    endpoint: otel-collector:13133

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, otlp]
    traces: 
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]  
    
